# Generated by Django 5.2.11 on 2026-03-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_appointment_date_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appointment_time',
        ),
    ]
