# Generated by Django 5.2.11 on 2026-03-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_payment_appointment'),
        ('consultations', '0002_consultation_fee_consultationfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='consultation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='consultations.consultation'),
        ),
    ]
