# Generated by Django 5.2.11 on 2026-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_payment_payment_method_onlineconsultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineconsultation',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
