# Generated by Django 5.2.11 on 2026-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_payment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
