# Generated by Django 5.2.11 on 2026-03-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_insurance_payment_insurance_number_and_more'),
        ('patients', '0003_remove_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.insurance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
