# Generated by Django 5.2.11 on 2026-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
